name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build for Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o sshm-linux-amd64

      - name: Build for macOS intel amd64
        run: GOOS=darwin GOARCH=amd64 go build -o sshm-darwin-amd64

      - name: Build for macOS apple arm64
        run: GOOS=darwin GOARCH=arm64 go build -o sshm-darwin-arm64

      - name: Build for Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -o sshm-windows-amd64.exe

      - name: Build for Windows arm64
        run: GOOS=windows GOARCH=arm64 go build -o sshm-windows-arm64.exe

      - name: Test
        run: go test -v ./...

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sshm-linux-amd64
            sshm-darwin-amd64
            sshm-darwin-arm64
            sshm-windows-amd64.exe
            sshm-windows-arm64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}