name: Go

on:
  push:
    branches: [ "main" ] 
    tags:
      - 'v*'

  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -o my-go-app

      - name: Test
        run: go test -v ./...

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./my-go-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}