name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout repository
      - uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Build executabilul Go
      - name: Build
        run: go build -o sshm

      # Testează codul
      - name: Test
        run: go test -v ./...

      # Crează un release pe GitHub și adaugă executabilul
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./sshm  # Adaugă executabilul generat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}